# vim:ft=ansible:
---

- name: create kafka_exporter group
  group:
    name: "{{ kafka_exporter_group }}"
    state: present

- name: create kafka_exporter user
  user:
    name: "{{ kafka_exporter_user }}"
    comment: "User to run kafka_exporter"
    createhome: no
    shell: /bin/false
    group: "{{ kafka_exporter_group }}"
    state: present

- name: create kafka_exporter home directory
  file:
    state: directory
    path:  "{{ kafka_exporter_parent_dir }}"
    owner: "{{ kafka_exporter_user }}"
    group: "{{ kafka_exporter_group }}"

- name: download and untar kafka_exporter tarball
  unarchive:
    src: "{{ kafka_exporter_tarball_url }}"
    dest: "{{ kafka_exporter_parent_dir }}"
    remote_src: yes
    owner: "{{ kafka_exporter_user }}"
    group: "{{ kafka_exporter_group }}"
    creates: "{{ kafka_exporter_install_path }}"

- name: install service file
  template:
    src: kafka_exporter.service.j2
    dest: /etc/systemd/system/kafka_exporter.service
  notify:
    - restart kafka_exporter service

- name: start kafka_exporter service
  systemd:
    name: kafka_exporter
    state: started
    enabled: yes
  when: kafka_exporter_manage_service

